version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=default
        - MONGO_INITDB_ROOT_PASSWORD=default
    volumes:
      - data:/data
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 27018:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=default
      - ME_CONFIG_MONGODB_ADMINPASSWORD=default
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    data: {}
networks:
    default:
        name: mongo_network
